# Generated by Django 4.2 on 2023-04-10 19:58

from django.db import migrations, models
import django_composite_auto_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_code', django_composite_auto_field.fields.CompositeAutoField(max_length=250, prefix='AA', use_year=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestModelB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_code', django_composite_auto_field.fields.CompositeAutoField(max_length=250, prefix='BB', use_year=False, zeros=5)),
            ],
        ),
    ]
