# Generated by Django 4.2 on 2023-07-13 15:59

from django.db import migrations
import django_composite_auto_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodelb',
            name='custom_code',
            field=django_composite_auto_field.fields.CompositeAutoField(max_length=250, prefix='BBB', use_year=False, zeros=5),
        ),
    ]
